name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0
      - run: zig fmt --check *.zig src/*.zig

  install-sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: "./scripts/"

  build:
    strategy:
      matrix:
        target:
          - "x86_64-macos-none"
          - "aarch64-macos-none"
          - "aarch64-linux-gnu"
          - "x86_64-linux-gnu"
          - "x86-linux-gnu"
          - "x86_64-windows-msvc"
          - "x86-windows-msvc"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0
      - run: zig build -Dtarget=${{ matrix.target }}
      - run: zig build test

  install-script:
    runs-on: ubuntu-latest
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/AMythicDev/zigverm/main/scripts/install.sh | bash
      - run: ls ~/.zigverm/bin/
      - run: source ~/.bashrc
      - run: echo $PATH
      # - run: bash -c "source ~/.bashrc && zigverm"
