name: windows-installer
on:
  push:
    paths:
      - "src/zigverm-setup/main.zig"
    tags:
      - "*"
  pull_request:

jobs:
  install-on-windows:
    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: "0.15.2"
      - run: zig build run-zigverm-setup
